Repository KidneyOS/KidneyOS, pull requests merged in 2024-11, with the labels that each got.

#91 Add more RootFileSystem tests
  kernel/src/fs/fs_manager.rs
Labels: Kind/Enhancement, Module/File System

#76 Fix userspace pointer functions so they actually check if the pointer is valid
  kernel/src/fs/syscalls.rs
  kernel/src/mem/util.rs
  kernel/src/paging.rs
  kernel/src/user_program/syscall.rs
  shared/src/paging.rs
Labels: Kind/Enhancement

#128 RUSH Skeleton
  kernel/src/block/partitions/partition_core.rs
  kernel/src/drivers/input/input_core.rs
  kernel/src/main.rs
  kernel/src/rush/cd/mod.rs
  kernel/src/rush/clear/mod.rs
  kernel/src/rush/env.rs
  kernel/src/rush/ls/ls_config.rs
  kernel/src/rush/ls/ls_core.rs
  kernel/src/rush/ls/mod.rs
  kernel/src/rush/mod.rs
  kernel/src/rush/parser.rs
  kernel/src/rush/rush_core.rs
  kernel/src/threading/mod.rs
  shared/src/video_memory.rs
Labels: Kind/Feature

#104 Implementation of Frame Allocator and Subblock Allocator
  kernel/src/mem/buddy_allocator.rs
  kernel/src/mem/dummy_allocator.rs
  kernel/src/mem/frame_allocator.rs
  kernel/src/mem/frame_allocator/placement_algorithms.rs
  kernel/src/mem/mod.rs
  kernel/src/mem/subblock_allocator.rs
Labels: Module/Memory

#130 Implement 'pwd' and 'cd' with 'root_filesystem'
  kernel/src/rush/cd/mod.rs
  kernel/src/rush/mod.rs
  kernel/src/rush/parser.rs
  kernel/src/rush/pwd/mod.rs
Labels: Kind/Feature, RUSH
