Repository KidneyOS/KidneyOS, pull requests merged in 2024-10, with the labels that each got.

#71 Add partition support
  kernel/src/block/block_core.rs
  kernel/src/block/mod.rs
  kernel/src/block/partitions/mod.rs
  kernel/src/block/partitions/partition_core.rs
  kernel/src/drivers/ata/ata_channel.rs
  kernel/src/drivers/ata/ata_core.rs
  kernel/src/drivers/ata/ata_device.rs
  kernel/src/drivers/ata/ata_interrupt.rs
  kernel/src/main.rs
Labels: Module/File System, Kind/Feature

#74 Integrate Sleep Mutex into IDE Driver
  kernel/src/drivers/ata/ata_core.rs
  kernel/src/drivers/ata/ata_interrupt.rs
  kernel/src/main.rs
Labels: Kind/Enhancement, Module/Threading, Module/File System

#85 Fix Residual Characters when Scrolling in VideoMemoryWriter
  shared/src/video_memory.rs
Labels: Kind/Enhancement

#78 Add filesystem syscalls
  Cargo.lock
  kernel/Cargo.toml
  kernel/src/fs/fs_manager.rs
  kernel/src/fs/mod.rs
  kernel/src/fs/syscalls.rs
  kernel/src/main.rs
  kernel/src/system.rs
  kernel/src/threading/process.rs
  kernel/src/threading/thread_control_block.rs
  kernel/src/user_program/syscall.rs
  kernel/src/vfs/mod.rs
  kernel/src/vfs/tempfs.rs
  programs.mk
  programs/fs/.gitignore
  programs/fs/Makefile
  programs/fs/basic.c
  syscalls.mk
  syscalls/bindgen.toml
  syscalls/include/kidneyos.h
  syscalls/src/defs.rs
  syscalls/src/lib.rs
Labels: Module/File System, Kind/Feature
